apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaodiyanxuan-frontend
  namespace: ns-cxxiwxce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiaodiyanxuan-frontend
  template:
    metadata:
      labels:
        app: xiaodiyanxuan-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/379005109-lab/xiaodiyanxuan-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xiaodiyanxuan-frontend
  namespace: ns-cxxiwxce
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: xiaodiyanxuan-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xiaodiyanxuan-frontend
  namespace: ns-cxxiwxce
spec:
  ingressClassName: nginx
  rules:
  - host: lgpzubdtdxjf.sealoshzh.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xiaodiyanxuan-frontend
            port:
              number: 80
  tls:
  - hosts:
    - lgpzubdtdxjf.sealoshzh.site
    secretName: sealos-cert
