#!/bin/bash

echo "================================"
echo "等待GitHub Actions完成构建"
echo "================================"
echo ""
echo "1. 打开浏览器访问:"
echo "   https://github.com/379005109-lab/xiaodiyanxuan-fullstack/actions"
echo ""
echo "2. 查看最新的两个workflows:"
echo "   - Backend Build and Deploy"
echo "   - Frontend Build and Push"
echo ""
echo "3. 等待两个都显示绿色✅（大约10-15分钟）"
echo ""
echo "4. 然后运行以下命令强制更新:"
echo ""
echo "kubectl delete pod -l app=xiaodiyanxuan-api -n ns-cxxiwxce --kubeconfig='kubeconfig (7).yaml'"
echo "kubectl delete pod -l app=xiaodiyanxuan-frontend -n ns-cxxiwxce --kubeconfig='kubeconfig (7).yaml'"
echo ""
echo "5. 等待1分钟后测试"
echo ""
