apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiaodiyanxuan-api
  namespace: ns-cxxiwxce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiaodiyanxuan-api
  template:
    metadata:
      labels:
        app: xiaodiyanxuan-api
    spec:
      containers:
      - name: api
        image: ghcr.io/379005109-lab/xiaodiyanxuan-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: xiaodiyanxuan-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: xiaodiyanxuan-secrets
              key: jwt-secret
        - name: JWT_EXPIRE
          value: "7d"
        - name: CORS_ORIGIN
          value: "https://lgpzubdtdxjf.sealoshzh.site,http://localhost:3000,http://localhost:5173,*"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: xiaodiyanxuan-api
  namespace: ns-cxxiwxce
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: xiaodiyanxuan-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xiaodiyanxuan-api
  namespace: ns-cxxiwxce
spec:
  ingressClassName: nginx
  rules:
  - host: pkochbpmcgaa.sealoshzh.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xiaodiyanxuan-api
            port:
              number: 80
  tls:
  - hosts:
    - pkochbpmcgaa.sealoshzh.site
    secretName: sealos-cert
