apiVersion: apps/v1
kind: Deployment
metadata:
  name: duijie-nn
  namespace: ns-cxxiwxce
  labels:
    app: duijie-nn
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: duijie-nn
  template:
    metadata:
      labels:
        app: duijie-nn
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: nginx
        image: ghcr.io/379005109-lab/duijie-nn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: duijie-nn
  namespace: ns-cxxiwxce
  labels:
    app: duijie-nn
spec:
  type: ClusterIP
  selector:
    app: duijie-nn
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duijie-nn
  namespace: ns-cxxiwxce
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - duijie.xiaodiyanxuan.com
    secretName: duijie-nn-tls
  rules:
  - host: duijie.xiaodiyanxuan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duijie-nn
            port:
              number: 80
